theme: jekyll-theme-minimal
title: Eduardo Anaya's homepage
description: Bookmark this to keep an eye on my project updates!
layout: page
title: "PAGE-TITLE"
permalink: https://eduardoanaya64.github.io/about/contact
